#!/bin/csh -f

#SBATCH --time=03:10:00
#SBATCH --job-name=C_test
#SBATCH --ntasks=40
#SBATCH --constraint=sky
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o C2021log-%j.out


#######################################################################
#                  System Environment Variables
#######################################################################

umask 022

SECONDS=0

rm -f *.exe

echo '--------------------------------------------------'
echo 'gcc - Matrix Copy: Regular'
echo '--------------------------------------------------'

gcc test_copy_matrix.c -o test_copy_matrix-gcr.exe

./test_copy_matrix-gcr.exe 5000
./test_copy_matrix-gcr.exe 7000
./test_copy_matrix-gcr.exe 9000

echo '--------------------------------------------------'
echo 'gcc - Matrix Copy: Optimized'
echo '--------------------------------------------------'

gcc -Ofast test_copy_matrix.c -o test_copy_matrix-gco.exe
#gcc -O3 -march=native -mfpmath=sse test_copy_matrix.c -o test_copy_matrix-gco.exe

./test_copy_matrix-gco.exe 5000
./test_copy_matrix-gco.exe 7000
./test_copy_matrix-gco.exe 9000

echo '--------------------------------------------------'
echo 'gcc - Munchausen Number: Regular'
echo '--------------------------------------------------'

gcc test_munchausen_number.c -o test_munchausen_number-gcr.exe -lm

./test_munchausen_number-gcr.exe

echo '--------------------------------------------------'
echo 'gcc - Munchausen Number: Optimized'
echo '--------------------------------------------------'

gcc -Ofast test_munchausen_number.c -o test_munchausen_number-gco.exe -lm

./test_munchausen_number-gco.exe

echo '__________________________________________________'
echo 'Delete all executables'
echo '__________________________________________________'

ELAPSED="Elapsed: $(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"

rm -f *exe
